#***********************************************************************
#*                                                                     *
#*                  Copyright (c) 1985-2024, AMI.                      *
#*                                                                     *
#*      All rights reserved. Subject to AMI licensing agreement.       *
#*                                                                     *
#***********************************************************************

[LibraryClasses]
  IpmiPlatformLib|GenoaSiliconPkg/Library/IpmiPlatformLib/IpmiPlatformLib.inf
  HwResetSystemLib|GenoaSiliconPkg/Library/BaseResetSystemLib/BaseResetSystemLib.inf

[LibraryClasses.common.SEC]
  ResetSystemLib|GenoaSiliconPkg/Library/BaseResetSystemLib/BaseResetSystemLib.inf

[LibraryClasses.common.PEIM]


[LibraryClasses.common.DXE_SMM_DRIVER,LibraryClasses.common.SMM_CORE]


[Components.IA32]


[Components.X64]
